//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Resources.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulo.
        /// </summary>
        public static string Circulo {
            get {
                return ResourceManager.GetString("Circulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculos.
        /// </summary>
        public static string Circulos {
            get {
                return ResourceManager.GetString("Circulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        public static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrados.
        /// </summary>
        public static string Cuadrados {
            get {
                return ResourceManager.GetString("Cuadrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figura.
        /// </summary>
        public static string Figura {
            get {
                return ResourceManager.GetString("Figura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figuras.
        /// </summary>
        public static string Figuras {
            get {
                return ResourceManager.GetString("Figuras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma Geométrica.
        /// </summary>
        public static string FormaGeometrica {
            get {
                return ResourceManager.GetString("FormaGeometrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista vacía de formas.
        /// </summary>
        public static string ListaVacia {
            get {
                return ResourceManager.GetString("ListaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimetro.
        /// </summary>
        public static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangulo.
        /// </summary>
        public static string Rectangulo {
            get {
                return ResourceManager.GetString("Rectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangulos.
        /// </summary>
        public static string Rectangulos {
            get {
                return ResourceManager.GetString("Rectangulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Formas.
        /// </summary>
        public static string TituloReporte {
            get {
                return ResourceManager.GetString("TituloReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecio.
        /// </summary>
        public static string Trapecio {
            get {
                return ResourceManager.GetString("Trapecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecios.
        /// </summary>
        public static string Trapecios {
            get {
                return ResourceManager.GetString("Trapecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangulo.
        /// </summary>
        public static string Triangulo {
            get {
                return ResourceManager.GetString("Triangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulos.
        /// </summary>
        public static string Triangulos {
            get {
                return ResourceManager.GetString("Triangulos", resourceCulture);
            }
        }
    }
}
